credentials:
  openai_api_secret_key:
  slack_bot_user_oauth_token:

chatbot:
  model: gpt-3.5-turbo  # text-davinci-003, gpt-3.5-turbo
  temperature: 0.5
  max_tokens: 1024
  top_p: 1
  frequency_penalty: 0
  presence_penalty: 0